name: Simple Test Workflow
on: workflow_dispatch # Make sure this is present to allow manual run
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello World! GitHub Actions is running."
